services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  service-a:
    build: ./service-a
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq
      - redis

  service-b:
    build: ./service-b
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq
      - redis