services:
  rabbitmq:
    image: rabbitmq:4-management
    ports:
      - 5672:5672
      - 15672:15672

  service-a:
    build: ./service-a
    ports:
      - "3000:3000"
    depends_on:
      - rabbitmq

  service-b:
    build: ./service-b
    ports:
      - "3001:3000"
    depends_on:
      - rabbitmq